import type { Metadata } from "next";
import { Quicksand} from "next/font/google";
import { AuthProvider } from "./auth-provider";
import './global.scss'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({ subsets: ["latin"], weight: ["300", "400", "700"], });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={quicksand.className}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
